services:
  producer:
    build: ./producer
    ports:
      - "50051:50051"
  consumer:
    build: ./consumer
    environment:
      PRODUCER_HOST: producer
    depends_on:
      producer:
        condition: service_started